root: /home/stef/krxns
data: ${.root}/data
artifacts: ${.root}/artifacts
configs: ${.root}/configs
raw_data: ${.data}/raw
processed_data: ${.data}/processed
interim_data: ${.data}/interim
mlruns: ${.artifacts}/mlruns
hpo_studies: ${.artifacts}/hpo_studies
coreactants: ${.artifacts}/coreactants
rules: ${.artifacts}/rules