source_names:
- H2O
- CoA
- ATP
- O2
- NADP(+)
- NADPH
- NAD(+)
- diphosphate
- NADH
- phosphate
- ADP
- CO2
- S-adenosyl-L-methionine
- S-adenosyl-L-homocysteine
- UDP
- AMP
- NH4(+)
- H2O2
- acetyl-CoA
- hydrogen sulfide
- methane
