defaults:
  - filepaths: filepaths
  - _self_

mechinformed_mapped: mapped_sprhea_240310_v3_mapped_no_subunits_x_mechinformed_rules.parquet
rc_plus_0_mapped: mapped_sprhea_240310_v3_mapped_no_subunits_x_rc_plus_0_rules.parquet

hydra:
  run:
    dir: ${filepaths.processed_data}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.processed_data}
    subdir: .