defaults:
  - filepaths: filepaths
  - sources: default
  - _self_

mechinformed_mapped: mapped_known_reactions_x_mechinformed_rules.parquet
rc_plus_0_mapped: mapped_known_reactions_x_rc_plus_0_rules.parquet
known_compounds: known_compounds.parquet

hydra:
  run:
    dir: ${filepaths.processed_data}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.processed_data}
    subdir: .